from __future__ import annotations

from dataclasses import dataclass
from datetime import UTC, datetime

from app.grpc.mappers import CitationEntry, ConversationTurnResult, TraceEntry, bootstrap_proto_modules
from app.llm.openai_compatible import OpenAICompatibleClient, build_openai_compatible_client

bootstrap_proto_modules()

from app.gen.proto.ai import runtime_pb2


@dataclass(slots=True)
class ChatQAAgent:
    llm_client: OpenAICompatibleClient | None = None

    def __post_init__(self) -> None:
        if self.llm_client is None:
            self.llm_client = build_openai_compatible_client()

    def answer(self, request: runtime_pb2.RunConversationTurnRequest) -> ConversationTurnResult:
        answer = self.llm_client.complete(f"Chat response: {request.message.strip()}")
        citations = [
            CitationEntry(
                source="chat_qa",
                title="Conversation guidance",
                snippet="Deterministic response generated by the Python runtime skeleton.",
                score=0.5,
            )
        ] if request.message.strip() else []

        return ConversationTurnResult(
            answer=answer,
            citations=citations,
            route="chat_qa",
            trace=[
                TraceEntry(
                    stage="chat_qa",
                    message="answered with deterministic chat skeleton",
                    timestamp=datetime.now(UTC).isoformat(),
                )
            ],
        )
